development:
  NEXT_PUBLIC_ENV: 'development'
  RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED: false
  NEXT_PUBLIC_API_BASE_URL: 'https://dev.domain.com/api'

stage:
  NEXT_PUBLIC_ENV: 'stage'
  RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED: false
  NEXT_PUBLIC_API_BASE_URL: 'https://domain.com/api'

production:
  NEXT_PUBLIC_ENV: 'production'
  RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED: false
  NEXT_PUBLIC_API_BASE_URL: 'https://domain.com/api'
